execute if predicate too_many_portals:suitable/floor/-2_-2 positioned ~-2 ~ ~-2 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-1_-2 positioned ~-1 ~ ~-2 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/0_-2 positioned ~ ~ ~-2 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/1_-2 positioned ~1 ~ ~-2 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-2_-1 positioned ~-2 ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-1_-1 positioned ~-1 ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/0_-1 positioned ~ ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/1_-1 positioned ~1 ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-2_0 positioned ~-2 ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-1_0 positioned ~-1 ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/0_0 positioned ~ ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/1_0 positioned ~1 ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-2_1 positioned ~-2 ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/-1_1 positioned ~-1 ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/0_1 positioned ~ ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/floor/1_1 positioned ~1 ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create
