execute if predicate customportals:suitable/z/-1_0_-1 positioned ~-1 ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/-1_1_-1 positioned ~-1 ~1 ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/-1_0_0 positioned ~-1 ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/-1_1_0 positioned ~-1 ~1 ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/-1_0_1 positioned ~-1 ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/-1_1_1 positioned ~-1 ~1 ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/0_0_-1 positioned ~ ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/0_1_-1 positioned ~ ~1 ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/0_0_0 positioned ~ ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/0_1_0 positioned ~ ~1 ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/0_0_1 positioned ~ ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/0_1_1 positioned ~ ~1 ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/1_0_-1 positioned ~1 ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/1_1_-1 positioned ~1 ~1 ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/1_0_0 positioned ~1 ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/1_1_0 positioned ~1 ~1 ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/1_0_1 positioned ~1 ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/z/1_1_1 positioned ~1 ~1 ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create_z