execute if predicate too_many_portals:suitable/z/-1_0_-1 positioned ~-1 ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/-1_1_-1 positioned ~-1 ~1 ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/-1_0_0 positioned ~-1 ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/-1_1_0 positioned ~-1 ~1 ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/-1_0_1 positioned ~-1 ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/-1_1_1 positioned ~-1 ~1 ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/0_0_-1 positioned ~ ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/0_1_-1 positioned ~ ~1 ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/0_0_0 positioned ~ ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/0_1_0 positioned ~ ~1 ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/0_0_1 positioned ~ ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/0_1_1 positioned ~ ~1 ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/1_0_-1 positioned ~1 ~ ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/1_1_-1 positioned ~1 ~1 ~-1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/1_0_0 positioned ~1 ~ ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/1_1_0 positioned ~1 ~1 ~ run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/1_0_1 positioned ~1 ~ ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z
execute unless score $created_portal too_many_portals matches 1 if predicate too_many_portals:suitable/z/1_1_1 positioned ~1 ~1 ~1 run function too_many_portals:portals/{{ too_many_portals.portal.dimension_a_id }}/{{ too_many_portals.portal.dimension_b_id }}/generate/create_z