execute if predicate customportals:suitable/floor/-2_-2 positioned ~-2 ~ ~-2 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-1_-2 positioned ~-1 ~ ~-2 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/0_-2 positioned ~ ~ ~-2 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/1_-2 positioned ~1 ~ ~-2 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-2_-1 positioned ~-2 ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-1_-1 positioned ~-1 ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/0_-1 positioned ~ ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/1_-1 positioned ~1 ~ ~-1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-2_0 positioned ~-2 ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-1_0 positioned ~-1 ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/0_0 positioned ~ ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/1_0 positioned ~1 ~ ~ run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-2_1 positioned ~-2 ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/-1_1 positioned ~-1 ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/0_1 positioned ~ ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
execute unless score $created_portal customportals matches 1 if predicate customportals:suitable/floor/1_1 positioned ~1 ~ ~1 run function customportals:portals/{{ customportals.portal.dimension_a_id }}/{{ customportals.portal.dimension_b_id }}/generate/create
